# Generated by Django 4.0.4 on 2022-06-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0004_masterdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark_Attendance2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('time1', models.IntegerField()),
                ('ip_address', models.CharField(max_length=100)),
                ('date1', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=200)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='att.masterdata2', to_field='stuid')),
            ],
            options={
                'unique_together': {('uid', 'date1'), ('date1', 'ip_address')},
            },
        ),
    ]
